name: personal_ai_teacher
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # Routing
  go_router: ^13.2.0

  # Networking
  dio: ^5.4.1

  # UI & UX
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9

  # Firebase
  firebase_core: ^4.2.0
  firebase_ai: ^3.4.0

  # Local Storage
  shared_preferences: ^2.2.2

  # Audio
  flutter_tts: ^4.2.3

  # Utils
  intl: ^0.20.2
  equatable: ^2.0.5
  path_provider: ^2.1.2
  uuid: ^4.3.3

  awesome_notifications: ^0.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  # Enable localization
  generate: true