const Map<String, String> russianStrings = {
  'notificationText': 'Готовы к новому вызову? Откройте для себя новый курс!',
  'deleteCourseTitle': 'Удалить курс',
  'deleteCourseConfirmation': 'Вы уверены, что хотите удалить "{courseTitle}"? Весь прогресс будет потерян.',
  'cancel': 'Отмена',
  'delete': 'Удалить',
  'generationFailedTitle': 'Ошибка генерации',
  'generationFailedText': 'Не удалось создать курс. Пожалуйста, попробуйте еще раз с другим текстом или темой.',
  'ok': 'OK',
  'unitCompleteTitle': 'Раздел пройден!',
  'unitCompleteText': 'Поздравляем с завершением раздела:',
  'continue': 'Продолжить',
  'exitLessonTitle': 'Вы уверены?',
  'exitLessonText': 'Если вы выйдете сейчас, ваш прогресс в этом уроке будет потерян.',
  'stayInLesson': 'Остаться',
  'leave': 'Выйти',
  'courseJsonTitle': 'JSON курса',
  'qaTitle': 'Вопросы и ответы',
  'promptsTitle': 'Промпты для генерации',
  'promptQa': 'Промпт для Q&A',
  'promptCourse': 'Промпт для курса',
  'appTitle': 'AI Учитель',
  'yourCourses': 'Ваши курсы',
  'suggestCourse': 'Предложить',
  'createNew': 'Создать новый',
  'mistakesCount': '{count} ошибки для повторения',
  'reviewMistakes': 'Повторить ошибки ({count})',
  'noCoursesTitle': 'Курсов пока нет',
  'noCoursesText': 'Начните с создания своего первого курса.',
  'createNewCourse': 'Создать новый курс',
  'back': 'Назад',
  'suggestionsTitle': 'Идеи для курсов',
  'suggestionsText': 'Вот несколько идей для начала.',
  'suggestionsLoading': 'Генерируем идеи...',
  'suggestionsError': 'Не удалось сгенерировать предложения.',
  'suggestionsErrorGeneral': 'Произошла ошибка при получении предложений.',
  'textInputTitle': 'Создать новый курс',
  'textInputText': 'Вставьте любой текст (не менее 50 символов) - статью, рассказ, концепцию - и мы превратим его в интерактивный курс для вас.',
  'textInputError': 'Пожалуйста, введите не менее 50 символов для создания курса.',
  'textInputPlaceholder': 'Вставьте ваш текст сюда...',
  'generateCourse': 'Создать курс',
  'tryDemo': 'Попробовать демо',
  'completed': 'Завершено',
  'start': 'Начать',
  'locked': 'Закрыто',
  'startLesson': 'Начать урок: {title}',
  'viewQa': 'Смотреть Q&A',
  'viewPrompts': 'Смотреть промпты',
  'viewJson': 'Смотреть JSON',
  'errorNoCourse': 'Ошибка: Не выбран активный курс.',
  'errorNoLesson': 'Ошибка: Нет урока для отображения.',
  'errorGeneral': 'Произошла непредвиденная ошибка.',
  'listenWritePlaceholder': 'Напишите, что слышите...',
  'context': 'Контекст',
  'meaningAssessmentPlaceholder': 'Объясните ваше понимание...',
  'correctAnswer': 'Правильный ответ: {answer}',
  'expectedIdea': 'Ожидаемая идея: {idea}',
  'correct': 'Правильно!',
  'incorrect': 'Неправильно',
  'checking': 'Проверка...',
  'check': 'Проверить',
  'loading': 'Загрузка...',
  'loadingSubtext': 'Пожалуйста, подождите.',
  'progressAnalyzing': 'Анализ текста...',
  'progressBuilding': 'Построение структуры курса...',
  'progressGeneratingQuestions': 'Генерация вопросов для: {title}',
  'newCourse': 'Новый курс',
  'heartsModalTitle': 'Закончились сердца!',
  'heartsModalText': 'Вам нужны сердца, чтобы начать новый урок. Сердца восстанавливаются со временем.',
  'lessonFailedModalTitle': 'Урок провален',
  'lessonFailedModalText': 'У вас закончились сердца для этого урока. Не волнуйтесь, вы сможете попробовать снова позже!',
  'imperfectCompletionModalTitle': 'Урок завершен!',
  'imperfectCompletionModalText': 'Отличная работа! Вы допустили несколько ошибок, но справились. Продолжайте практиковаться!',
};