const Map<String, String> englishStrings = {
  'notificationText': 'Ready for a new challenge? Discover a new course!',
  'deleteCourseTitle': 'Delete Course',
  'deleteCourseConfirmation': 'Are you sure you want to delete "{courseTitle}"? All progress will be lost.',
  'cancel': 'Cancel',
  'delete': 'Delete',
  'generationFailedTitle': 'Generation Failed',
  'generationFailedText': 'We couldn\'t create the course. Please try again with a different text or topic.',
  'ok': 'OK',
  'unitCompleteTitle': 'Unit Complete!',
  'unitCompleteText': 'Congratulations on completing the unit:',
  'continue': 'Continue',
  'exitLessonTitle': 'Are you sure?',
  'exitLessonText': 'If you leave now, your progress in this lesson will be lost.',
  'stayInLesson': 'Stay',
  'leave': 'Leave',
  'courseJsonTitle': 'Course JSON',
  'qaTitle': 'Questions & Answers',
  'promptsTitle': 'Generation Prompts',
  'promptQa': 'Q&A Prompt',
  'promptCourse': 'Course Prompt',
  'appTitle': 'AI Teacher',
  'yourCourses': 'Your Courses',
  'suggestCourse': 'Suggest',
  'createNew': 'Create New',
  'mistakesCount': '{count} mistakes to review',
  'reviewMistakes': 'Review {count} Mistakes',
  'noCoursesTitle': 'No courses yet',
  'noCoursesText': 'Get started by creating your first course.',
  'createNewCourse': 'Create New Course',
  'back': 'Back',
  'suggestionsTitle': 'Course Suggestions',
  'suggestionsText': 'Here are a few ideas to get you started.',
  'suggestionsLoading': 'Generating ideas...',
  'suggestionsError': 'Could not generate suggestions.',
  'suggestionsErrorGeneral': 'An error occurred while fetching suggestions.',
  'textInputTitle': 'Create a New Course',
  'textInputText': 'Paste in any text (at least 50 characters) - an article, a story, a concept - and we will turn it into an interactive course for you.',
  'textInputError': 'Please enter at least 50 characters to generate a course.',
  'textInputPlaceholder': 'Paste your text here...',
  'generateCourse': 'Generate Course',
  'tryDemo': 'Try a Demo',
  'completed': 'Completed',
  'start': 'Start',
  'locked': 'Locked',
  'startLesson': 'Start lesson: {title}',
  'viewQa': 'View Q&A',
  'viewPrompts': 'View Prompts',
  'viewJson': 'View JSON',
  'errorNoCourse': 'Error: No active course selected.',
  'errorNoLesson': 'Error: No lesson to display.',
  'errorGeneral': 'An unexpected error occurred.',
  'listenWritePlaceholder': 'Type what you hear...',
  'context': 'Context',
  'meaningAssessmentPlaceholder': 'Explain your understanding...',
  'correctAnswer': 'Correct answer: {answer}',
  'expectedIdea': 'Expected idea: {idea}',
  'correct': 'Correct!',
  'incorrect': 'Incorrect',
  'checking': 'Checking...',
  'check': 'Check',
  'loading': 'Loading...',
  'loadingSubtext': 'Please wait a moment.',
  'progressAnalyzing': 'Analyzing text...',
  'progressBuilding': 'Building course structure...',
  'progressGeneratingQuestions': 'Generating questions for: {title}',
  'newCourse': 'New Course',
  'heartsModalTitle': 'Out of Hearts!',
  'heartsModalText': 'You need hearts to start a new lesson. Hearts refill over time.',
  'lessonFailedModalTitle': 'Lesson Failed',
  'lessonFailedModalText': 'You\'ve run out of hearts for this lesson. Don\'t worry, you can try again later!',
  'imperfectCompletionModalTitle': 'Lesson Complete!',
  'imperfectCompletionModalText': 'Great job! You made a few mistakes, but you pushed through. Keep practicing!',
};